Initial PMIC interfacing, changes in logging function[added log type]…
DatavenueLiveObjects/LiveObjects_SDK_for_Arduino pull request #1
Opened 2020-08-03 11:07 UTC by krzysztofkrzeslak

…, SSID validation, added ip in network info

2020-08-06 15:27 UTC, mdelain requested changes
`addPowerStatus()` seems to freeze the board :(
Tested on LTE-M & GSM boards

> It seems that `Wire.Begin()` is too far away from the requests made inside `LiveObjectsBase::addPowerStatus()`.
> I made a simple test by disabling the `batteryBegin()` function (by doing so, I disabled the first `Wire.Begin()`), and adding the `Wire.Begin()` directly before the I2C requests in `readRegister()`
```c++
byte readRegister(byte address) {
    Wire.begin();   // added here
    Wire.beginTransmission(PMIC_ADDRESS);
    Wire.write(address);

    if (Wire.endTransmission(true) != 0) {
      return -1;
    }

    if (Wire.requestFrom(PMIC_ADDRESS, 1, true) != 1) {
      return -1;
    }

    return Wire.read();
}
```
> It seems to work smoothly now.

> The behavior is strange on the MKR VIDOR, it says that a battery is connected even if not (!). I searched a bit but didn't find any information for the moment. It's the same PMIC though.

2020-08-06 16:29 UTC, mdelain requested changes
One more left in `Utils.cpp` : https://github.com/DatavenueLiveObjects/LiveObjects_SDK_for_Arduino/blob/50b3d4e2d4a590efc82b6ea91abf990030874a36/src/Utils.cpp#L26

2020-08-06 16:34 UTC, mdelain requested changes
You need to add a specific hack for MKR1000, because it doesn't support TLS.
So choosing TLS should trigger a stop in the code.

2020-08-06 16:34 UTC, mdelain commented on src/LiveObjects.cpp
> +  outputDebug(INFO,"Publishing message on topic", topic);
There is a missing space after "topic", leading to something like
_[INFO] Publishing message on **topicdev/data**_

2020-08-06 16:39 UTC, mdelain requested changes
You could add support of ARDUINO_SAMD_MKRVIDOR4000 (using WiFiNINA library). However as PMIC is not working properly for now (see in PMIC comments), let's not define it as compatible with the feature.

2020-08-07 06:35 UTC, krzysztofkrzeslak commented
1. Seem that on the MKR1500 issue was that the address of charging IC was swapped in comparison to MKRWIFI1010, should be fixed now, can you check if this is also true for MKR Vidor?
2. Serial.println() in utils is not a mistake as output debug can be used only in the LiveObjects class.

2020-08-11 11:01 UTC, krzysztofkrzeslak commented
No more change requests, requested ones already done, merging to master.

2020-08-11 11:06 UTC, merged